stages:
  - build
  - deploy

variables:
  IMAGE_NAME: wishlist-app
  CONTAINER_NAME: wishlist-app
  PORT: 9201

build:
  stage: build
  script:
    - docker build \
        --build-arg S3_ENDPOINT=$S3_ENDPOINT \
        --build-arg S3_PORT=$S3_PORT \
        -t $IMAGE_NAME .
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

deploy:
  stage: deploy
  script:
    - docker stop $CONTAINER_NAME || true
    - docker rm $CONTAINER_NAME || true
    - docker run -d \
        --name $CONTAINER_NAME \
        -p $PORT:$PORT \
        -e DB_URL=$DB_URL \
        -e S3_ACCESS_KEY=$S3_ACCESS_KEY \
        -e S3_SECRET_KEY=$S3_SECRET_KEY \
        -e S3_BUCKET_NAME=$S3_BUCKET_NAME \
        -e S3_ENDPOINT=$S3_ENDPOINT \
        $IMAGE_NAME
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

